### PR TITLE
Added ConvertMetresToLengthUnits() Method

### PR DESCRIPTION
**Pull request by hartkemd**
Hi, Pierre. I made a method that converts metres to other units of length. I'm sure it's not totally perfect, but it's something we can start with, and I think it's in the spirit of what you were doing. I also renamed the Length enum to LengthUnits, which seemed to make more sense to me. If you don't like it, you're welcome to change it back. One last thing I did was to re-wire the UI work I did previously, to allow us to test the new conversion method I added.

### CODE REVIEW

**Comment by hartkemd** [comment]
Sorry, I think I should have split up my commits into more bite-sized chunks.. I'll try to do that next time.

**Comment by pjlplourde** [comment]
I don;t think this one fits with the direction I was going and has a number of conflicting files.  If you want to refresh your fork and justg add your ConvertMetresToLengthUnits method as a separate method called from ConvertLength when the input units are metres, that would work as a good model to follow for the rest of the conversions.

**Comment by hartkemd** [comment]
Sorry, took me a while to wrap my head around what was going on in Git, but I think I got it.
Is something like this what you had in mind?

**Comment by pjlplourde** [comment]
Thank you for the work. It's appreciated.

**Pull request merged**
